centreon/centreon-test-lib

- src/behat/ServiceDowntimeConfigurationPage.php
Modification of the test for the new location of the recurrent downtime.
Associate with the pull request **Recurrent downtimes #4831**
> Modify path for the recurrent downtimes

- src/behat/CentreonContext.php
- src/behat/CurrentUserConfigurationPage.php
- src/behat/ParametersCentreonUiPage.php
Add function and details for the autologin acceptance.
> Modify several files for the autologin acceptance

- src/behat/Configuration/RecurrentDowntimeConfigurationPage.php
Configure recurrent downtime acceptance test has been fix, the value of $validField attribute in RecurrentDowntimeConfigurationPage class has been changed
> Downtime start and stop.

- src/behat/Configuration/ContactGroupConfigurationListingPage.php
Properties added and getId added.
> ContactGroupConfigurationListing was updated

- src/behat/Administration/LdapConfigurationListingPage.php
- src/behat/Administration/LdapConfigurationPage.php
Administration/LdapConfigurationListingPage and Administration/LdapConfigurationPage have been created for acceptance tests
> LdapConfiguration

- src/behat/Administration/LdapConfigurationListingPage.php
- src/behat/Administration/LdapConfigurationPage.php
spelling mistake fixed in LdapConfigurationPage.php (enable_authentication) and a "status" property added in LdapConfigurationListingPage.php
> Ldap configuration

- src/behat/ConfigurationPage.php
getProperties method enhanced, with a possibility to pass an array in argument to choose what will be return, and a getProperty method has been added
> Method enhancement

- src/behat/ListingPage.php
New method created, selectMoreAction()
> New method in listingPage.php

- src/behat/Configuration/SnmpTrapsConfigurationListingPage.php
The variable objectClass was missing
> SnmpTrapsConfigurationListingPage fixed

- src/behat/Administration/ACLGroupConfigurationListingPage.php
id property and getId method added
> ACLGroupConfigurationListingPage updated

- src/behat/Administration/ACLGroupConfigurationPage.php
the 'status' property has been added
> ACLGroupConfigurationPage update

- src/behat/Monitoring/MetricsConfigurationListingPage.php
- src/behat/Monitoring/MetricsConfigurationPage.php
virtualsMetrics config pages created
> virtualsMetrics

- src/behat/Monitoring/MetricsConfigurationListingPage.php
- src/behat/Monitoring/MetricsConfigurationPage.php
> Virtuals metrics

- src/behat/CentreonContext.php
2 methods added getServiceWithSeveralMetrics() and iAmLoggedInACentreonServerWithAConfiguredMetrics()
> enhancement of CentreonContext, facto.

- src/behat/CentreonContext.php
> Centreon context enhancement

- src/behat/Monitoring/MonitoringServicesPage.php
properties attributes, setFilterByAllService() and  getPropertyFromAHostAndService() function added.
> Monitoring service page enhance

- src/behat/CentreonContext.php
iAmLoggedInACentreonServerWithAConfiguredProxy() new method add, used as a background in TestConfigurationProxyContext
> 5561 feat(admin) add a Proxy configuration to centreon test-lib 

- src/behat/RestApiContext.php
Feature class for use the docker to test Centreon Rest API test
> Add Feature class for call the Centreon Rest API test

- src/behat/RestApiContext.php
Pass only the docker name, but not the docker server
> feat(behat): Simplify the docker name on scenario

- src/behat/RestApiContext.php
Fix for testing the new postman mechanism
> fix(behat): Fix the use path and add constant for registry uri

- src/behat/CentreonContext.php
Can choose if the feature flipping is activate
> New header 2.8.x

- src/behat/Configuration/CommentHostConfigurationPage.php
- src/behat/Configuration/CommentListingPage.php
- src/behat/Exception/ClosureException.php
- src/behat/Monitoring/HostMonitoringDetailsPage.php
- src/behat/Monitoring/ServiceMonitoringDetailsPage.php
- src/behat/UtilsContext.php
> enh(test): Test the XSS vulnerability on hosts and services comments

- src/behat/Configuration/PollerResourceConfigurationListingPage.php
- src/behat/Configuration/PollerResourceConfigurationPage.php
- src/behat/Exception/ClosureException.php
- src/behat/UtilsContext.php
Create acceptance tests to check existance of the XSS vulnerability on the poller resrouce list page.
> enh(test): Test the XSS vulnerability on poller resource

- src/mock/CentreonDB.php
- src/traits/TestCaseExtensionTrait.php
extend CentreonDB to reset result sets and add ability to set/get protected property with TestCaseExtensionTrait
Resolve MON-3235
> feat(test): improvments of Mocks and Traits

- src/behat/Extensions/ContainerExtension.php
This PR should be merged on all supported branches.
> Rename mon-web-influxdb.yml to mon-web-influxdb-dev.yml

- src/behat/CentreonContext.php
- src/behat/UtilsContext.php
With a WebDriver per test, we can record test video and provide it as an artifact in case of failure.
Related to centreon/centreon-build#112.
This should be merged on all supported branches.
> Record test video.

- src/behat/UtilsContext.php
This should fix multiple acceptance tests of Centreon Web.
> fix(test): try recommended command-line argument to work around Chrome popup bug

- src/behat/Container.php
This should fix current issue where containers are attempted to be created multiple times.
> Run /docker-compose up/ only once.

- src/behat/Monitoring/MonitoringServicesPage.php
After fixing the behavior of the listing page in the monitoring service, we need to update the related acceptance test.
> fix(monitoring). Change the position of the columns to retrieve their data

- src/behat/Administration/ACLMenuConfigurationPage.php
poller wizard access wizard has been removed from acl menu page
Then, checkbox ids have been updated
Refs: MON-4049 MON-3218
> test(acceptance): update acl menu page selectors

- src/behat/Administration/ACLGroupConfigurationListingPage.php
- src/behat/Administration/ACLGroupConfigurationPage.php
- src/behat/Administration/BackupConfigurationPage.php
- src/behat/Administration/LdapUserImportPage.php
- src/behat/Configuration/DowntimeConfigurationListingPage.php
- src/behat/Configuration/PollerConfigurationListingPage.php
- src/behat/ConfigurationPage.php
- src/behat/External/LoginPage.php
- src/behat/Home/CustomViewsPage.php
- src/behat/ListingPage.php
- src/behat/Monitoring/MonitoringHostsPage.php
- src/behat/Monitoring/MonitoringServicesPage.php
- src/behat/Monitoring/ServiceMonitoringDetailsPage.php
- src/behat/Page.php
- src/behat/UtilsContext.php
> enh(style): update acceptance tests to match material style

- src/behat/CentreonContext.php
Updates the login process to work correctly with the new version of behat/mink
> fix(connection): Fix the login process for the new version of behat/mink

- src/behat/CentreonAPIContext.php
> feat(test): extend CentreonAPIContext to check value by pattern

- src/behat/CentreonAPIContext.php
> feat(test): Extend CentreonAPIContext to compare the response by pattern

- src/behat/CentreonAPIContext.php
> fix(test): payload when is empty for request have to be array not null

- src/behat/CentreonContext.php
> feat(test): made describing of feature file much more flexible

- composer.json
- src/PHPStan/AbsolutePathErrorFormatter.php
This formatter allow to export absolute paths needed by jenkins plugin "violation comments"
Refs: MON-4910
> feat(ci): create phpstan error formatter

- src/behat/CentreonContext.php
**WARNING**
This PR can only be merged after the creation of 19.10.x and/or 19.04.x maintenance branch(es) ! Changes should be reflected in the _composer.json_ and _composer.lock_ files of projects using _centreon-test-lib_.
> Retrieve Gorgone logs intead of Centcore.

- src/behat/Api/Context/ApiContext.php
- src/behat/Api/Context/JsonContextTrait.php
* fix base uri on module's containers
* Avoid to repeat full local path for validation
Refs: MON-5020
> fix(api): fix base uri on module's containers

- composer.json
- composer.lock
- src/behat/Api/Context/ApiContext.php
- src/behat/Api/Context/JsonContextTrait.php
- src/behat/Api/Context/RestContextTrait.php
This allow to validate api endpoints using documentation (validate typing, routes, required arguments)
> feat(api): add api documentation validation

- src/behat/Api/Context/ApiContext.php
- src/behat/Api/Context/FileSystemContextTrait.php
- src/behat/Api/Context/JsonContextTrait.php
Create filesystem trait to check content of a file
> enh(api): add filesystem trait to check content of a file

- src/behat/UtilsContext.php
Increase select2 spin value to avoid timeout failure
> enh(chore): increase select2 spin timeout

- src/behat/Api/fixtures/validation/monitoring/resource/listing.json
https://github.com/centreon/centreon/pull/9186
> fix(api) resources return alias and fqdn

- src/behat/Api/fixtures/validation/monitoring/resource/listing.json
remove impact_resources_count property in resources listing endpoint
Refs: MON-6319
> enh(api): remove impact_resources_count property

- src/behat/Api/Context/ApiContext.php
- src/behat/Api/Context/FileSystemContextTrait.php
- src/behat/Api/Context/RestContextTrait.php
add possibility to select a specific version of documentation to check endpoints.
> enh(api): add possibility to select specific documentation version to check endpoints

- src/behat/Api/Context/JsonContextTrait.php
- src/behat/Api/Context/RestContextTrait.php
* use last api documentation version
* improve api testing debug by displaying received content
> enh(api): use last doc version + improve debug

- src/behat/Api/Context/ApiContext.php
- src/behat/Api/Context/RestContextTrait.php
- src/behat/CentreonContext.php
Replace all beta endpoints by latest
> enh(api) Update all API access points to the new version 21.10

- src/behat/Api/Context/ApiContext.php
- src/behat/Api/fixtures/validation/configuration/monitoring-servers/generate_reload.json
Added TA to generate and reload the monitoring server configuration
> enh(conf/poller): Added TA to generate and reload the monitoring server configuration

- src/behat/Api/Context/ApiContext.php
- src/behat/Api/Context/CentreonClapiContextTrait.php
- src/behat/CentreonAPIContext.php
- src/behat/CentreonContext.php
according to recent changes on the new password security policy, all the passwords in centreon-test-lib needs to be updated to fit the new default policy. (1uppercase, 1lowercase, 1digit, 1special character, 12 characters length).
This PR is merged on a feature branch, and will be merged on master when the `centreon:password-security-policy` branch will be merged on develop.
> Update passwords in centreon test lib

- composer.json
- composer.lock
> chors(deps): upgrade dependencies

- src/behat/Api/Context/RestContextTrait.php
it will allow to set it from class wich extend ApiContext
> enh(api): set apiValidator to protected

- src/behat/Container.php
fix compatibility with docker-compose v2
> fix(behat): fix compatibility with docker-compose v2

- .gitignore
- composer.json
- composer.lock
- src/PHPStan/CustomRules/AbstractGetLoggerMethodsClass.php
- src/PHPStan/CustomRules/Collectors/MethodCallCollector.php
- src/PHPStan/CustomRules/CustomRuleErrorMessage.php
- src/PHPStan/CustomRules/LogMethodInCatchCustomRule.php
- src/PHPStan/CustomRules/LoggerUseCaseCustomRule.php
- src/PHPStan/CustomRules/StringBackquotesCustomRule.php
- src/PHPStan/CustomRules/VariableLengthCustomRule.php
- src/PHPStan/phpstan.neon
- tests/PHPStan/CustomRules/LogMethodInCatchCustomRuleTest.php
- tests/PHPStan/CustomRules/LoggerUseCaseCustomRuleTest.php
- tests/PHPStan/CustomRules/StringBackquotesCustomRuleTest.php
- tests/PHPStan/CustomRules/VariableLengthCustomRuleTest.php
Implemented log custom PHPStan rules:
- LoggerTrait should be imported and used in UseCase
- Catch block should have a log method (info / error / critical etc )
Implemented unit tests for log custom rules.
**Fixes** # MON-14310
> feat(phpstan) implementation of log custom rules

- src/behat/Container.php
- src/behat/Monitoring/MetricsConfigurationPage.php
* wait result to select metric in virtual metric page
* properly select container port
**Fixes** MON-14359
> fix(test): wait result to select metric in virtual metric page

- src/PhpCsFixer/PhpCsFixerRuleSet.php
Jira : MON-16094
_Nothing to test._
> update php cs-fixer

- src/behat/Api/Context/ApiContext.php
This PR intends to fix correct status code check on API Container
> fix(apiContext): check correct status code on container launch

- src/behat/CentreonContext.php
fix(engine): wait centreon engine is totally reloaded (#224)
> fix(engine): wait centreon engine is totally reloaded (#224)

- src/behat/CentreonContext.php
Fix logout request
Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.
Any **relevant details** of the configuration to perform the test should be added.
> fix(behat) logout request is called with GET verb

- src/behat/Api/Context/JsonContextTrait.php
> fix: not working test "And the JSON node :node should not exist"

- src/behat/Container.php
Since we've integrated profiles into our dockerfiles, the step that should stop the container after behat tests no longer works.
> fix (test/behat): Added profile name to stop containers

- src/behat/Configuration/HostTemplateConfigurationPage.php
- src/behat/Configuration/ServiceTemplateConfigurationPage.php
PR needed for https://github.com/centreon/centreon/pull/1871
> enh(behat): remove enabled option from template forms

- src/Command/Model/FileTemplate.php
- src/PhpCsFixer/PhpCsFixerLicense.php
- src/PhpCsFixer/PhpCsFixerRuleSet.php
Jira: 🏷️ MON-17226
**Fixes** # (issue)
> fix(php-cs-fixer): update of PhpCsFixerRuleSet

- src/behat/Container.php
enh(docker): add compatiblity to latest docker compose logs
**Fixes** MON-20421
> enh(docker): add compatiblity to latest docker compose logs

- src/behat/CentreonContext.php
update chrome capabilities and force debugging port
> enh(test): update chrome capabilities and force debugging port

- src/behat/Api/Context/ApiContext.php
- src/behat/CentreonContext.php
- src/behat/Container.php
- src/behat/RestApiContext.php
enh(test): use new syntax of docker compose and add --wait
> enh(test): use new syntax of docker compose and add --wait

- src/PhpCsFixer/PhpCsFixerLicense.php
Update current year
**Fixes** # (issue)
> chore(ci): update current year

- src/PhpCsFixer/PhpCsFixerLicense.php
Correct datetime namespace
**Fixes** # (issue)
> fix(ci): correct datetime namespace

- src/behat/Api/Context/RestContextTrait.php
This PR intends to update the centreon-test-lib documentation check method regarding the latest changes done on the API documentation.
> enh(test): update centreon doc check mechanism to latest doc changes

- src/behat/Configuration/HostConfigurationPage.php
- src/behat/Configuration/HostTemplateConfigurationPage.php
- src/behat/Configuration/MassiveChangeHostConfigurationPage.php
Update legacy test lib for host and host templates forms
> enh(conf/legacy): update legacy configuration forms tests

- .editorconfig
- .gitattributes
- composer.json
- composer.lock
- rector.php
- src/PhpCsFixer/PhpCsFixerRuleSet.php
- src/behat/Administration/ExtensionsPage.php
- src/behat/Api/Context/ApiContext.php
- src/behat/CentreonContext.php
- src/behat/Configuration/RecurrentDowntimeConfigurationPage.php
- src/behat/ConfigurationPage.php
- src/behat/RestApiContext.php
- src/mock/Centreon.php
- src/mock/CentreonUser.php
* phpcompatibility added
* .editorconfig and .gitattributes at the project root to force LF and UTF8
* upgrade to php8.2
* composer.json updated (scripts, platform 8.2, require-dev, style)
* rector configuration updated
> enh: upgrade to php 8.2

- src/behat/Configuration/PollerConfigurationListingPage.php
fix(behat): avoid stale element in poller configuration listing page
> fix(behat): avoid stale element in poller configuration listing page
