centreon/centreon-test-lib

src/behat/Configuration/MassiveChangeHostConfigurationPage.php

*2.8* branch.
This option was removed from the Centreon Web interface and is therefore useless.

fix(test): remove massive change option for contact groups in host configuration page

---

src/behat/CentreonContext.php

In previous code WebDriver was only waited for availability. However
when using Grid, WebDriver can be reported as available whereas no
node is available.

fix(test): wait for available WebDriver node.

---

src/behat/Monitoring/ServiceMonitoringDetailsPage.php

Update the monitoring details file which gets properties from the page. Change the way DateTime is created for the last_check property, which no longer uses the Y/m/d - H:i:s format.

test(monitoring): update date format check

---

src/behat/ConfigurationPage.php

there is a problem with checkboxes and radio buttons in 19.04.x because the parent is "td" element and somehow doesn't throw an exception on click event
Resolve BAM-806

Improve the ContifurationPage::setProperties to properly handling with old checkboxes and radio buttons

---

src/behat/Configuration/HostTemplateConfigurationListingPage.php
src/behat/Configuration/HostTemplateConfigurationPage.php

The calls were made on host creation witch tried to switchToIframe even when already on iFrame. 60 sec were lost everytime due to the spin

enh(test): avoid useless switchToIframe calls

---

src/behat/Api/Context/ApiContext.php
src/behat/Api/Context/JsonContextTrait.php
src/behat/Api/Context/RestContextTrait.php

**Usage :** 
```
Given I send a GET request to '/beta/monitoring/hosts
And I store response values in:
| name   | path         |
| hostId | result[0].id |
When I send a GET request to '/beta/monitoring/hosts/<hostId>/timeline'
```

feat(api): allow to store result section in variable

---

composer.json
src/behat/CentreonContext.php

Sometimes, acceptance tests fails randomly on login page.
It seems to be related to centreon token, which is not initialized.
Don't want to waste more time on 2.8, so I set a spin on login..

fix(acceptance): fix random fails on login page

---

composer.json
composer.lock

The league/openapi-psr7-validator library uses the league/uri library. The latter, since version 6.5.0, no longer supports PHP 7.2.x.
We have to force the version of the league/uri library to 6.4.0

fix(depedencies) Force version on dependencies

---

src/behat/Administration/ParametersCentreonUiPage.php

remove centreon web path option
**Fixes** MON-12893

enh(platform): remove centreon web path option

---

src/behat/Monitoring/MetricsConfigurationPage.php

Since we changed the "select" by select2 of the "list of metrics" in Monitoring > Performances > Virtual Metrics, they made a regression in some of acceptance tests, this PR should take care of it.
**Fixes** # MON-14359

fix(tests): Fixing Metrics acceptance tests

---

src/behat/Monitoring/MetricsConfigurationPage.php

Since we changed the "select" by select2 of the "list of metrics" in Monitoring > Performances > Virtual Metrics, they made a regression in some of acceptance tests, this PR should take care of it.
**Fixes** # MON-14359

fix(tests): Fixing Metrics acceptance tests 21.10.x

---

src/behat/Monitoring/MetricsConfigurationPage.php

Since we changed the "select" by select2 of the "list of metrics" in Monitoring > Performances > Virtual Metrics, they made a regression in some of acceptance tests, this PR should take care of it.
**Fixes** # MON-14359

fix(tests): Fixing Metrics acceptance tests 21.04.x

---

src/PHPStan/CustomRules/ArchitectureRules/ExceptionInUseCaseCustomRule.php
src/PHPStan/CustomRules/RepositoryRules/RepositoryMethodReturnCustomRule.php
tests/PHPStan/CustomRules/ArchitectureRules/ExceptionInUseCaseCustomRuleTest.php

This PR adapts PHPStan Exception Custom rule to exclude constructor methods from checking.
It contains :
- implementation of additional checks to exclude constructor methods
- implementation of unit tests for constrauctor methos case
**Fixes** # MON-14778

fix(phpstan) implement a particular case in exception custom rule 

---

src/behat/Api/Context/ApiContext.php

Added the method to be able to use a non-admin user in tests.
**Fixes** # MON-15254
How To Test
Test 1:
- In a .feature  file (e.g LocalProviderConfiguration) use a CLAPI Import to create user that doesnt have access to api configuration
- Use the context I am Logged In With :username/:password
- The endpoints should not be accessible
Test 2:
- In a .feature  file (e.g LocalProviderConfiguration) use a CLAPI Import to create user that has access to api configuration
- Use the context I am Logged In With :username/:password
- The endpoints should be accessible

feat(behat): Add a Context to be able to use a user under ACL in tests

---

src/behat/Api/Context/ApiContext.php
src/behat/Api/Context/JsonContextTrait.php
src/behat/Api/Context/RestContextTrait.php

This PR intends to add the possibility to replace macros set from previous API call in the method "JSON is equal to:"
Example
```
[........]
And I send a GET request to '/api/v23.04/monitoring/services?search={"$and":[{"host.name":"test"},{"service.description":"test_service_1"}]}'
And I store response values in:
| name      | path              |
| hostId    | result[0].host.id |
| serviceId | result[0].id      |
When I send a GET request to '/api/latest/bam/configuration/indicators?search={"name": {"$lk": "%test_service_1%"}}'
Then the response code should be "200"
And the JSON should be equal to:
"""
{
"result": [
{
"uuid": "h<hostId>-s<serviceId>",
"name": "test - test_service_1",
"type": "service",
"short_type": "s",
"resource": {
"id": <serviceId>,
"parent_id": <hostId>
},
"enabled": …
```

replace macros for JSON is equal to

---

src/behat/CentreonContext.php

fix(engine): wait centreon engine is totally reloaded by checking "Configuration reloaded" in centreon-engine logs

fix(engine): wait centreon engine is totally reloaded

---

src/PhpCsFixer/PhpCsFixerRuleSet.php
src/PhpCsFixer/license.apache.txt
src/PhpCsFixer/license.private.txt

> Normalize headers with php-cs-fixer code style rule set.
Jira: 🏷️ **MON-18017**
Run php-cs-fixer manually.

feat(php-cs-fixer): dynamic headers in code style

---

src/behat/Home/CustomViewsPage.php
src/behat/UtilsContext.php

fix(test): make select2 selection resilient : 
* use jquery to search and select
* add assertions for focus, highlight, selection and closing

fix(test): make select2 selection resilient

---

src/behat/Api/Context/RestContextTrait.php

fix theHeaderShouldBeEqualTo() and theHeaderShouldNotBeEqualTo() methods in RestContextTrait for Behat testing
(getHeader return an array of string and not a string)

fix(api/behat) tests on headers

---

src/behat/Api/Context/ApiContext.php
src/behat/Api/Context/CentreonClapiContextTrait.php

reload acl on debian with www-data user
**Fixes** MON-20805

fix(api): reload acl on debian with www-data user

---

src/behat/Api/Context/JsonContextTrait.php

fix(api): avoid sprintf format error when asserting a json with %

fix(api): avoid sprintf format error when asserting a json with %

---

src/PhpCsFixer/PhpCsFixerRuleSet.php

feat: split the PhpCsFixerRuleSet into 2 lists : safe + risky

---

src/behat/Container.php
src/behat/SpinTrait.php

add retry mechanism to docker compose start and stop
cherry-picked from https://github.com/centreon/centreon-test-lib/commit/62a3517742929f37706c24839ab3ed1332287b4e

fix(test): add retry mechanism to docker compose start and stop

---

src/PhpCsFixer/PhpCsFixerRuleSet.php

Removal of the php-cs-fixer rule concerning date verification in PHP file headers

fix (php-cs-fixer): removal date verification in PHP file headers

---

src/behat/CentreonContext.php

This PR intends to remove Chrome broken flag following update to chrome 128. This flag is used by Panther when the Behat tests are executed

fix(panther): remove Chrome broken flag following update to chrome 128

---

src/mock/CentreonDB.php

Fixed the issue where method signature mismatch breaks unit tests in https://github.com/centreon/centreon-modules/pull/3849
**Fixes** # (issue)

fix(Method): Method signature doesn't match

---

src/PHPStan/CustomRules/MiscRules/VariableLengthCustomRule.php

Missing comma causes issue with phpstan excecution

fix(rule): missing comma in possible exception names array

---

src/behat/Container.php

* due to recent changes in runner configuration, docker daemon only listens on unix socket and not tcp
* added a condition specific to unix socket docker_host
**Fixes** #MON-163849
Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.
Any **relevant details** of the configuration to perform the test should be added.

fix(ci): handle unix socket based runner config for docker daemon

---

src/behat/Container.php

fix(ci): handle unix socket based runner config
- due to recent changes in runner configuration, docker daemon only listens on unix socket and not tcp
- added a condition specific to unix socket docker_host
Fixes #MON-163849
Please describe the **procedure** to verify that the goal of the PR is matched. Provide clear instructions so that it can be **correctly tested**.
Any **relevant details** of the configuration to perform the test should be added.

fix(ci): handle unix socket based runner config for docker daemon (#265)

---

src/behat/Administration/ImageListingPage.php

Changed assetion type on Image Listing Page for media folder synchronisation
**Fixes** # MON-167547-ACL-medias

fix(Behat): Changed assetion type on Image Listing Page for media folder synchronisation
